# Web功能已移除

# API
API:
  # Network Configuration
  Host_IP: 0.0.0.0    # default IP | 默认IP
  Host_Port: 80    # default port is 80 | 默认端口为80
  Docs_URL: /docs    # API documentation URL | API文档URL
  Redoc_URL: /redoc    # API documentation URL | API文档URL

  # API Information
  Version: V4.1.2    # API version | API版本
  Update_Time: 2025/03/16    # API update time | API更新时间
  Environment: Demo    # API environment | API环境

  # Download Configuration
  Download_Switch: true    # Enable download function | 启用下载功能

  # File Configuration
  Download_Path: "./download"    # Default download directory | 默认下载目录
  Download_File_Prefix: "douyin.wtf_"    # Default download file prefix | 默认下载文件前缀


# iOS Shortcut
iOS_Shortcut:
  iOS_Shortcut_Version: 7.0
  iOS_Shortcut_Update_Time: 2024/07/05
  iOS_Shortcut_Link: https://www.icloud.com/shortcuts/06f891a026df40cfa967a907feaea632
  iOS_Shortcut_Link_EN: https://www.icloud.com/shortcuts/06f891a026df40cfa967a907feaea632
  iOS_Shortcut_Update_Note: 重构了快捷指令以兼容TikHub API。
  iOS_Shortcut_Update_Note_EN: Refactored the shortcut to be compatible with the TikHub API.

# Aitable.ai Configuration
Aitable:
  api_key: "uskIZVNT6ybBEQxO5cTPcCa"    # 你的Aitable.ai API Key (Bearer Token)
  base_id: "dstGGELxSrPMb0kRWa"    # 你的Aitable.ai Datasheet ID
  table_name: "viwMgMZrxb1Zv"    # View ID
